name: flutter_chat
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.20.1
  firebase_auth: ^3.6.3
  google_sign_in: ^5.4.1
  cloud_firestore: ^3.4.4
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5+3
  shared_preferences: ^2.0.15
  firebase_storage: ^10.3.5
  intl: 0.17.0
  firebase_messaging: ^12.0.2
  flutter_local_notifications: ^9.7.0
  photo_view: ^0.14.0
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
